INSERT INTO parametro(familia, producto) VALUES ('Tarjetas', 'Clasica');
INSERT INTO parametro(familia, producto) VALUES ('Tarjetas', 'Oro');
INSERT INTO parametro(familia, producto) VALUES ('Tarjetas', 'Black');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '1');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '2');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '3');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '4');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '5');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '6');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '7');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '8');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '9');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '10');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '11');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '12');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '13');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '14');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '15');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '16');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '17');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '18');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '19');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '20');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '21');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '22');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '23');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '24');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '25');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '26');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '27');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '28');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '29');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '30');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '31');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '32');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '33');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '34');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '35');
INSERT INTO parametro(familia, producto) VALUES ('Cuotas', '36');
INSERT INTO parametro(familia, producto) VALUES ('DiasPago', '5');
INSERT INTO parametro(familia, producto) VALUES ('DiasPago', '20');
INSERT INTO parametro(familia, producto) VALUES ('TEA', '99.90%');
INSERT INTO parametro(familia, producto) VALUES ('TEA', '95.90%');
INSERT INTO parametro(familia, producto) VALUES ('TEA', '90.90%');

INSERT INTO persona(dni, nombre, apellido, correo, tarjeta) VALUES ('10602933', 'Jim', 'Morrison', 'jim.morrison@gmail.com', 'Clasica');
INSERT INTO persona(dni, nombre, apellido, correo, tarjeta) VALUES ('30102931', 'Marco', 'Vito', 'Marco.Vito@gmail.com', 'Oro');
INSERT INTO persona(dni, nombre, apellido, correo, tarjeta) VALUES ('30622937', 'Pedro', 'Pecaldri', 'Pedro.Pecaldri@gmail.com', 'Black');
INSERT INTO persona(dni, nombre, apellido, correo, tarjeta) VALUES ('70007630', 'Maria', 'Rambosi', 'Maria.Rambosi@gmail.com', 'Clasica');
INSERT INTO persona(dni, nombre, apellido, correo, tarjeta) VALUES ('50605936', 'Camilo', 'Trason', 'Camilo.Trason@gmail.com', 'Oro');
INSERT INTO persona(dni, nombre, apellido, correo, tarjeta) VALUES ('190605936', 'Pepe', 'Martan', 'Pepe.Martan@gmail.com', 'Black');
